import stdio
import sys

# Get x, y, and z from command line, as ints.
x = ...
y = ...
z = ...

# If x, y, and z are all equal, ie, x equals y and y equals z, then
# write "equal". Otherwise, write "not equal".
if ...:
    ...
else:
    ...
